//
//  ViewController.swift
//  AV Foundation
//
//  Created by Pranjal Satija on 5/22/17.
//  Copyright © 2017 Pranjal Satija. All rights reserved.
//

import UIKit
import Photos

class ViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    ///Allows the user to put the camera in photo mode.
    @IBOutlet fileprivate var photoModeButton: UIButton!
    @IBOutlet fileprivate var toggleCameraButton: UIButton!
    @IBOutlet fileprivate var toggleFlashButton: UIButton!
    
    ///Allows the user to put the camera in video mode.
    @IBOutlet fileprivate var videoModeButton: UIButton!
    @IBOutlet weak var previewImage: UIImageView!
    @IBOutlet weak var previewBtn: UIButton!
    @IBOutlet weak var previewImageRatio: NSLayoutConstraint!
    
    let cameraController = CameraController()
    
    override var prefersStatusBarHidden: Bool { return true }
    
    // 得到最後一張照片（https://www.learnfk.com/question/swift/30812057.html）
    // https://www.raywenderlich.com/11764166-getting-started-with-photokit
    func getAssetThumbnail() {
        PHPhotoLibrary.requestAuthorization({ (status) in
            if status != .authorized {
                print("不允許存取照片")
                return
            }
            //取得相簿第一張照片放到preview
            let result = PHAsset.fetchAssets(with: .image, options: nil)
            guard let result = result.lastObject else {
                print("Loading preview image failed.")
                return
            }
            let manager = PHImageManager.default()
            let option = PHImageRequestOptions()
            option.isSynchronous = true
            DispatchQueue.main.async {
                manager.requestImage(for: result, targetSize: CGSize(width: self.previewImage.frame.width, height: 70), contentMode: .aspectFit, options: option, resultHandler: {(result, info) -> Void in
                    self.previewImage.image = result
                })
            }
            
        })
    }
    
}

extension ViewController {
    override func viewDidLoad() {
        
        //計算螢幕比例，改變左下預覽比例
        let ratio = self.view.frame.height / self.view.frame.width
        previewImage.backgroundColor = .black
        previewImage.layer.cornerRadius = 5
        previewImageRatio.constant = ratio
        previewBtn.layer.cornerRadius = 5
        
        //取得相簿第一張照片放到preview
        getAssetThumbnail()
        
        ///設置好相機
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                try? self.cameraController.displayPreview(on: self.capturePreviewView)
            }
        }
        
        ///拍攝按鈕
        func styleCaptureButton() {
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2
            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }
        
        configureCameraController()
        styleCaptureButton()
        
    }
}

extension ViewController {
    
    @IBAction func toggleFlash(_ sender: UIButton) {
        if cameraController.flashMode == .on {
            cameraController.flashMode = .off
            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash Off Icon"), for: .normal)
        }
            
        else {
            cameraController.flashMode = .on
            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash On Icon"), for: .normal)
        }
    }
    
    @IBAction func switchCameras(_ sender: UIButton) {
        do {
            try cameraController.switchCameras()
        }
        catch {
            print(error)
        }
        
        switch cameraController.currentCameraPosition {
        case .some(.front):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "Front Camera Icon"), for: .normal)
            
        case .some(.rear):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "Rear Camera Icon"), for: .normal)
            
        case .none:
            return
        }
    }
    
    @IBAction func captureImage(_ sender: UIButton) {
        //按鈕反灰
        captureButton.isEnabled = false
        captureButton.backgroundColor = .gray
        cameraController.captureImage {(image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
            
            try? PHPhotoLibrary.shared().performChangesAndWait {
                PHAssetChangeRequest.creationRequestForAsset(from: image)
            }
            //按鈕恢復
            self.captureButton.isEnabled = true
            self.captureButton.backgroundColor = .white
            
            //把底層照片換成拍攝前的最後一張
            if let lastImage = self.previewBtn.currentImage {
                self.previewImage.image = lastImage
            }
            
            //把剛拍的照片放到previewBtn做縮放動畫
            self.previewBtn.alpha = 0
            self.previewBtn.transform = CGAffineTransform(scaleX: 0.1, y: 0.1)
            self.previewBtn.setBackgroundImage(image, for: .normal)
            UIView.animate(withDuration: 0.3) {
                self.previewBtn.alpha = 1
                self.previewBtn.transform = CGAffineTransform(scaleX: 1, y: 1)
            }

        }
    }
    
}

